version: "3.8"

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_USER: onlineaid
      MONGO_PASS: password
      # MONGO_IPAD: mongo
      # MONGO_PORT: 27017
    command: ["npm", "run", "dev"]

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: onlineaid
      MONGO_INITDB_ROOT_PASSWORD: password
