version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: onlineaid
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/:/data/db/

# Is create a vloume name check docker vloume ls
volumes:
  mongo:
    name: mongo_volume_data # it will set your custom volume name


  # mongo:
  #   image: mongo
  #   restart: always
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: onlineaid
  #     MONGO_INITDB_ROOT_PASSWORD: password
  # volumes:
  #   - ./db_data/:/data/db/
